"""empty message

Revision ID: 550bc753cb96
Revises: 2ec8f0c43c0d
Create Date: 2019-07-15 17:17:55.305783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550bc753cb96'
down_revision = '2ec8f0c43c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
